name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - run: .\build.bat
        shell: cmd
      - run: gh release create "${{ github.ref_name }}" --generate-notes pfemu.exe
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
